### ISSUE TITLE
BUG - Error Creating Windows

### ISSUE THREAD

**Issue by Grimm33** [Yuvix25/ReHUD#11]
**Describe the bug**
Rehud no longer working, tried reinstalling multiple times but was not successful. Running Rehud gives this error - [11] ERROR - Error creating windows. 

**To Reproduce**
not sure, worked fine for over a month but it suddenly broke

**Expected behavior**
Expected the reinstall to fix the issue

**Screenshots**

**ReHUD Version:** 
0.10.0-beta

**Additional context**

**Log file**
[ReHUD.log](https://github.com/user-attachments/files/17926019/ReHUD.log)

**Comment by Yuvix25** [comment]
Looks like you're reaching some quota for the WMI service, see if [this guide](https://learn.microsoft.com/en-us/troubleshoot/windows-server/system-management-components/wmi-error-0x8004106c) helps.
May I also ask which Windows version are you using?

FYI @rcbevans - maybe you have some additional insight on this?

**Comment by Grimm33** [comment]
Windows version attached ![image-1.png](https://github.com/user-attachments/assets/99f49a26-32d4-492c-b48c-92daa235484d)

**Comment by Grimm33** [comment]
Fixed this. The resource you provided gave me this error ![image](https://github.com/user-attachments/assets/1ba271b5-a329-4076-acdc-e26b7f864d2e), and when i googled it i found that a reason for this would happen was when the firewall blocked Windows Management Instrumentation. Unblocked the WMI and it works now.

**Comment by rcbevans** [comment]
I suspect that this machine might have a high up time and the wmi logs are big.

@Grimm33 do you reboot often, and does it work if you reboot?

How much ram does your system have?

@Yuvix25 we might be able to add a "within N" to the WMI query to pull fewer rows in the query.

https://stackoverflow.com/a/26340200

**Comment by rcbevans** [comment]
Oh I missed your comment saying it was working. Glad you figured it out!
