### ISSUE TITLE
Lights

### ISSUE THREAD

**Issue by Tuna350Z** [Yuvix25/ReHUD#6]
I can not see startin lights? Is there such feature?

**Comment by Yuvix25** [comment]
Starting lights are not and will not be implemented in ReHUD.
To enable the default in-game lights, make sure you removed all of the Steam launch parameters (which you probably have as a left over from OtterHud or similar).

**Comment by Tuna350Z** [comment]
Deleting all of the Steam launch parameters helped. Thanks a lot.
