### ISSUE TITLE
Rehud disappears when R3E is active

### ISSUE THREAD

**Issue by peterkasbergen** [Yuvix25/ReHUD#9]
**Describe the bug**
ReHud is visible over R3E when the game does not have focus. It disappears when the game gets focus.

**To Reproduce**
Click outside R3E or alt-tab away.

**Expected behavior**
That ReHUD is visible when the game has focus.

**Screenshots**
Not necessary, I think. :)

**ReHUD Version:**
v0.9.1 beta

**Additional context**
Happens in both D3D and Vulkan versions. Also in Windowed and Borderless Windowed mode.

**Log file**
Attach the `ReHUD.log` file which can be found by clicking on "Show Log File" in the ReHUD settings window.
[ReHUD.log](https://github.com/user-attachments/files/17233993/ReHUD.log)

**Comment by peterkasbergen** [comment]
Bug is found when NOT using Hardware Acceleration. When using Hardware Acceleration, ReHUD is not visible at all.

**Comment by Yuvix25** [comment]
Odd. Using Nvidia surround or anything similar?
Any chance you can record a video of this happening?
So far these issues were always resolved by using borderless windowed and one of the hardware acceleration options.

**Comment by peterkasbergen** [comment]
I am using Nvidia Surround. Not much to record, really. When the game has no focus, the overlays show over R3E. When I click on the game window, the overlay disappears. Tried windowed and borderless. Also tried HA and non-HA. All have the same result.

**Comment by peterkasbergen** [comment]
Update: In DX9 mode, the overlay is visible, but seems disconnected from the game. Tyres are black and no data is showing anywhere.

**Comment by Yuvix25** [comment]
Is it always disconnected or only sometimes?
I did get the disconnected issue a few times but a restart always fixed it.

**Comment by peterkasbergen** [comment]
So far, it's always.

**Comment by Yuvix25** [comment]
Hmmm, no idea then. I'll try adding some more logs in areas which might be relevant for future versions, hopefully they'll catch something.

**Comment by Yuvix25** [comment]
@peterkasbergen Have you tried renaming/removing your Documents/ReHUD folder?

**Comment by peterkasbergen** [comment]
Just tried removing the Documents/ReHUD folder. No change. Recap: It works fine in DX9. With Vulkan, it shows when R3E does NOT have focus. Click on the R3E window and the overlay disappears.

ReHUD looks great though. Hope we can get this solved.

**Comment by peterkasbergen** [comment]
I Googled around a bit. Found this, which is for another game, but exactly describes my issues. Seems it's a general Vulkan issue: https://www.reddit.com/r/pathofexile/comments/gtb84j/important_thing_about_vulkan_renderer_seems_that/

**Comment by Yuvix25** [comment]
Ah ok, this is a known issue. Vulkan doesn't properly configure borderless windowed.  
You previously said the issue also occurs with D3D - hence my confusion.
> Happens in both D3D and Vulkan versions. Also in Windowed and Borderless Windowed mode.

Some people in the DIscord wrote that reducing the game resolution by 1 pixel fixes it, and someone also posted a solution which involves changing Nvidia settings. Not sure if any of those actually work, feel free to have a look in the `#apps` channel over at the official RaceRoom Discord server.

**Comment by peterkasbergen** [comment]
Sorry about the confusion. I read the solutions, but will stick to using Otterhud with Vulkan or ReHUD with DX9 for now. Whichever I feel like. I hope the DXVK and/or Vulkan devs fix this issue.

**Comment by Yuvix25** [comment]
Sounds good. Closing for now, feel free to re-open if necessary.

**Comment by Shadowphoenix** [comment]
@Yuvix25 since i just wasted a good half an hour diagnosing this: wouldnt it make sense to mention this in the Readme under the how to install? just a quick reminder to set R3E to launch with DX9 instead of DXVK... maybe im blind but i didnt see anything about it.

EDIT: i took the freedom to make a pullrequest that edits the readme accordingly
